name: Run the tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Setup the project
        run: bundle install

      - name: Run the tests
        run: bundle exec rake
